# This GitHub Actions workflow demonstrates how to use the HashiCorp Terraform MCP Server (Docker) for a full IaC workflow.
# It runs on every push to main, and on pull requests for validation.
# Adjust the paths, secrets, and environment variables as needed for your project.

name: Terraform MCP Server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Terraform Init (MCP Server)
        run: |
          docker run --rm \
            -e ARM_CLIENT_ID \
            -e ARM_CLIENT_SECRET \
            -e ARM_SUBSCRIPTION_ID \
            -e ARM_TENANT_ID \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            hashicorp/terraform-mcp-server:latest init -input=false

      - name: Terraform Plan (MCP Server)
        run: |
          docker run --rm \
            -e ARM_CLIENT_ID \
            -e ARM_CLIENT_SECRET \
            -e ARM_SUBSCRIPTION_ID \
            -e ARM_TENANT_ID \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            hashicorp/terraform-mcp-server:latest plan -input=false -out=tfplan

      - name: Terraform Apply (MCP Server)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker run --rm \
            -e ARM_CLIENT_ID \
            -e ARM_CLIENT_SECRET \
            -e ARM_SUBSCRIPTION_ID \
            -e ARM_TENANT_ID \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            hashicorp/terraform-mcp-server:latest apply -input=false -auto-approve tfplan

      - name: Upload Terraform Plan as Artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
